### ISSUE TITLE
Error: unrecognized configuration parameter "server_version_num"

### ISSUE THREAD

**Issue by oguzhanogreden** [Borvik/vscode-postgres#107]
When I'm adding a database connection, after I type the database name at 6th step, I get the following error:

```
unrecognized configuration parameter "server_version_num"
```

When I type a database name that does not exist, the error becomes "it doesn't exist". So I'm guessing the connection is successful but there's something else going on.

Let me know if I can provide more information.

**Comment by Borvik** [comment]
`server_version_num` is part of a query to the server upon connection so that the correct queries are run when listing functions and tables that exist on the server.

Based on documentation `server_version_num` was introduced in 8.2, leading me to assume that the server you are attempting to connect to is a version prior to that or perhaps Amazon Redshift (which based on 8.0.2).

The earliest supported postgres version is 9.4. (which perhaps I should add to the readme)

**Comment by oguzhanogreden** [comment]
Indeed I'm trying to connect to Amazon Redshift.

Handling the error message and adding the key information to the error or a note in the readme would definitely make it easier to figure out :)
