### ISSUE TITLE
Getting error The function 'current_setting('server_version_num')' is an unknown form.  Check that the function name and number of arguments is correct.

### ISSUE THREAD

**Issue by EricLSD** [Borvik/vscode-postgres#144]
I'm getting the following error when setting up my connection:
```
The function 'current_setting('server_version_num')' is an unknown form.  Check that the function name and number of arguments is correct.
```
How might I work around this issue?  I have demonstrated that psql, from the command line will connect and query the same server and db.

**Comment by Borvik** [comment]
The first question would be - what kind of server are you connecting to?  Is it something like Amazon RedShift?

**Comment by EricLSD** [comment]
I'm connecting to a JDV environment supporting teiid.  The environment support jdbc connections using the teiid driver or postgres (with or without psycopg2).

**Comment by Borvik** [comment]
It's not postgres... The query you are posting about is attempting to get the Postgres version number so that it can determine which set of queries to use for querying metadata on columns/tables.

I know your not using RedShift, but I'll use that as an example - RedShift _is_ actually Postgres, but it's been heavily modified by Amazon to fit their purposes, and some queries have been restricted for security purposes.  Queries that this extension needs in order to run.

JDV - _isn't_ Postgres, and while the data transfer protocols may be the same and allow psql or other postgres drivers to work, the queries it supports just isn't the same.

Unfortunately it doesn't look like this extension will work for you.
