### ISSUE TITLE
Add table editor

### ISSUE THREAD

**Issue by mojo2012** [Borvik/vscode-postgres#145]
Hi,

first let me thank you for this neat little plugin!

What would be really cool to have is a table editor, like something like this:
![Bildschirmfoto 2020-08-19 um 20 00 58](https://user-images.githubusercontent.com/1330361/90672660-be89fb00-e256-11ea-8eab-60c5e2bef12e.png)

It allows to edit cells directly.

**Comment by Borvik** [comment]
As cool as it would be, I have examined the possibility before but came to the conclusion it wasn't feasible for me.

The plugin is about running arbitrary queries and seeing the results.  Really the question of an editor like that would be - how do you craft an arbitrary `UPDATE` statement for an arbitrary query?

1. `SELECT` statement may not have _any_ primary keys - how do you target the the update?
2. `SELECT` statement may have `joins` - now it has to update two tables - are all the primary keys available - how can you tell?
3. `SELECT` statement may have returned _multiple_ primary keys (due to joins), how can you tell which is for what cell updates?

When dealing with the just results of the query - you don't really have access to the necessary data to craft those updates.  You would definitely need an advanced query parser that you can match and only allow editing under the circumstances where you can guarantee proper updates.

The query parser in this plugin is so simplistic it can only separate multiple queries via the semi-colon.  Parsing for errors is actually done by the sql server via `EXPLAIN`.

**Comment by mojo2012** [comment]
I would not allow to edit arbitrary queries, but rather only one table at once.
Even if there is no PK, you can always have a `WHERE` clause that contains all the original column values:

## Original
| start | stop | notes |
| ---   | ---    |---      |
| 0       | 1      | test    |

## Changed
| start | stop | notes |
| ---   | ---    |---      |
| 0       | 1      | XXXX   |

## Update Query
```sql
UPDATE table
   SET notes = 'XXXX'
 WHERE start = 0
   AND stop  = 1
   AND notes = 'test'
```

**Comment by mojo2012** [comment]
I wonder then how all the other tools, like datagrip, do it? But why not just disable editing on tables without a pk?

**Comment by Borvik** [comment]
Again - this is a tool that only runs arbitrary SQL queries.  There is no parser to differentiate the query to a single table.  In order for editing to be viable, the parser would have to be able to identify queries that do not have joins, are not views, and do not contain calculated columns.

I know other tools _do_ have parsers built-in to them, this one does not.
