### ISSUE TITLE
Not Support Amazon Redshift ?

### ISSUE THREAD

**Issue by zengming00** [Borvik/vscode-postgres#18]
Hi, I tried to connect Amazon Redshift database, but got a error
```
database "postgres" does not exist
[Error - 23:36:35] (node:11388) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by zengming00** [comment]
Can I specify a specific database

**Comment by Borvik** [comment]
Currently no. Adding support for Redshift would need ongoing testing, and while I could sign up for the redshift trial, that would expire in 2 months and testing after that would then become problematic.

**Comment by CuteLemon** [comment]
It's still not working.
When I try to connect to a Redshift DB, I will get:
```
Connection to redshift: unrecognized configuration parameter "server_version_num" 
```

**Comment by Borvik** [comment]
In order to accommodate different/newer postgres versions some of the queries for getting the tables/columns had to be tweaked based on the version.  `server_version_num` is what is used to get that version.

Sounds like Amazon has locked that down too, which means Redshift will continue to be unsupported.
