### ISSUE TITLE
Output tab cannot be pinned to the second column

### ISSUE THREAD

**Issue by maksad** [Borvik/vscode-postgres#193]
**Description**: 
When running a query in the VsCode (using `Shift+Enter` in MacOs), the output tab opens in the second column, when rerunning the same query for the second time the output tab opens in the first column.

https://user-images.githubusercontent.com/4527650/148527967-3879508d-b59b-4f0f-ac6b-3afae32dfd18.mov

**Expected outcome**

Every time a query is run the output tab must open in the column it was opened before, instead of opening the tab in the first column.

**Comment by Borvik** [comment]
I can replicate this...

The problem comes from a `editor.reveal()` call that is used to focus the existing query result window to the foreground of it's respective panel in case it isn't already visible.

This _used_ to work fine, the recent vscode update I think changed something.

Even though it's being called to reveal in the same ViewColumn it's already in it appears to be switching, which I agree is highly annoying.

Still investigating, but this may be an issue with vscode and not the extension.

**Comment by Borvik** [comment]
https://github.com/microsoft/vscode/issues/138914

**Comment by bparkin1283** [comment]
Is this related to #84 ?

**Comment by Borvik** [comment]
no - not related to that one - but rather an actual vscode issue linked above

**Comment by bparkin1283** [comment]
This is fixed with the nightly vscode 1.64 build via microsoft/vscode#138914 via 57e2ed6.
