### ISSUE TITLE
It would be cool if there was a filter

### ISSUE THREAD

**Issue by superbotan** [Borvik/vscode-postgres#21]
for example
for hide pg_temp.... and pg_toast
or for search some function or table

**Comment by gb-jlofton** [comment]
I was thinking the same thing, this is an awesome extension for vs code, but being able to edit/hide certain tables would be really nice! Even if I had to manually go through each table that I wanted to 'hide' that would be excellent as well.

**Comment by Borvik** [comment]
The hiding/filtering part may not be too difficult - could add a command to the command palette that prompts for the search pattern.  The more challenging part would be an indicator and a way to clear that filter.  I've got a few ideas on that front that I was given during the webview upgrade.

**Comment by davidmach14** [comment]
Your extension was recommended to me by one of PostgreSQL core developers and it looks very promising. Not only because it's very fast. Object filter in the explorer window is an important feature for me because I work with databases that contain a large number of tables. Similar functionality is in DBeaver (see screenshot). Hope you implement this feature soon! :-) 
![dbeaver-object-filter](https://user-images.githubusercontent.com/6551719/48117033-28930500-e268-11e8-8d1b-2002562fe193.png)

**Comment by Borvik** [comment]
It would be cool.  Just looking for the proper way to implement it.  When a filter is in place - what gets filtered?  Database/schemas/tables/columns/functions - any or all the above?  How does DBeaver handle that functionality.

Currently I am unable to add a filter bar like that, however according to MS iteration plan for october (Microsoft/vscode#60106) there is "Tree widget performance improvements & filtering support" in the engineering section.  Perhaps that filtering support will work for this.

**Comment by Borvik** [comment]
MSs addition of tree filter works for this db explorer.  With the nodes expanded, if you type with the explorer focused it should filter automatically.
