### ISSUE TITLE
Display notification when error occurs

### ISSUE THREAD

**Issue by GammaGames** [Borvik/vscode-postgres#4]
I had a couple times when I would be trying to select from a table I didn't have permission for and it only prints things out into the "Output" panel, which I have hidden. A notification using vsc's built in notifications when an error occurs would be a nice enhancement

**Comment by Borvik** [comment]
Actually it probably is a good idea, especially as I plan to change how the query diagnostics work.  Currently a persistent connection is kept to the server and it repeated sends one or more EXPLAIN queries in order to do that problem checking.

Not really an optimal solution - just the quickest to implement.

I hope at some point to use a language parser augmented by a cache of the function/tables/views pulled from the database.  This would eliminate the need for a persistent connection - but would not catch some errors such as the permission you mentioned.

**Comment by Borvik** [comment]
Added in v1.0.3

**Comment by Borvik** [comment]
Yeah - that one will take a while - but it is planned.
