### ISSUE TITLE
SSL without validating certs

### ISSUE THREAD

**Issue by golyalpha** [Borvik/vscode-postgres#66]
Hi, I have an issue with accessing my app's DB hosted on Heroku, because Heroku requires SSL connection to be used if the connection is coming from outside Heroku's network. While it doesn't make my developement too much harder, I have to rely on tools like DataGrip in order to access the DB to read the data outside of my app. Is there a way to do this already, and I just missed it, or does this require a change to the code?

**Comment by Borvik** [comment]
See #54 for full details - but it boils down to, set the certificate path to a file, any file, and it will trigger SSL mode.

**Comment by golyalpha** [comment]
Interesting... So, does it mean that if someone sets a cert, it's actually not being used to validate the SSL connection?

**Comment by Borvik** [comment]
Yes/no...

It was originally implemented with perhaps either an incomplete or flawed understanding of how the SSL connection work specifically with the PG npm package (https://node-postgres.com/features/ssl).  It gets even more confusing as some 3rd party examples seem to indicate the ssl property could be a boolean.

Currently if a file is used in the configuration - it is passed in as the CA property, and that is all that is used - however it doesn't seem to be doing anything (probably because it is the only thing set).  It's existence however DOES trigger basic TLS.

**Comment by cornelco** [comment]
I'm having troubles getting the certPath set. I'm not sure what to use in the path. I can see that in the error message the SSL is set to off.

**Comment by dboune** [comment]
I set it to `/dev/null` on MacOS and it worked. Wacky.. but functional.

**Comment by Borvik** [comment]
This should be fixed in an upcoming release.

**Comment by Borvik** [comment]
Released in 1.1.9
