### ISSUE TITLE
Request: support default server

### ISSUE THREAD

**Issue by dwelle** [Borvik/vscode-postgres#69]
Support to make a connection a default for a project (for all files), or at least default, period.

**Comment by Borvik** [comment]
Actually this wouldn't be too bad to implement, but there is one decision to be made.

Currently the extension doesn't really load until a feature it provides is used (Language is selected, DB Explorer navigated to, or a command run from the command palette), and the status bar doesn't appear until the extension is loaded.

The question/decision is - so that files that are already open when vscode opens have a default connection, should the extension just load immediately all the time, or continue as it currently does and load when a feature is used?

**Comment by Borvik** [comment]
this should be available in 1.1.5

**Comment by dwelle** [comment]
Hmmm, that's a good question. Depends on what's the initialization cost. If it won't have effect on vscode load times or UI readiness, then I'd personally go with auto-initialization.
