### ISSUE TITLE
error: column p.proisagg does not exist on Postgres11

### ISSUE THREAD

**Issue by squaresun** [Borvik/vscode-postgres#72]
The following error occurred when connecting to Postgres 11:
`error: column p.proisagg does not exist `

In Postgres 11, proisagg and proiswindow, in pg_proc, are removed. Instead, pg_proc.prokind is used to state the corresponding property.

See the [doc](https://www.postgresql.org/docs/current/catalog-pg-proc.html) here.

And also, apart from only aggregate and window functions, handling on normal function and  procedure is needed?

**Comment by Borvik** [comment]
Just love it when PG changes stuff like that :).  Thanks for the report and the pull request, though I think I want to take a different route with how to manage that using the pg version number instead of column detection.  I'm also looking into some way to group some of these queries by version so they can be more easily referenced and swapped out as needed.

**Comment by Borvik** [comment]
I do have an implementation of this pending merge.  I'm hoping to do a little more work on the extension this weekend and a publish on Monday morning.

**Comment by Borvik** [comment]
This should be available in 1.1.5
